"""
配置参数模块
"""

# 应用信息
APP_NAME = "微信表情包制作工具"
APP_VERSION = "1.0.0"

# 微信表情包规格参数
WECHAT_STICKER_WIDTH = 240
WECHAT_STICKER_HEIGHT = 240
WECHAT_STICKER_MAX_SIZE_KB = 500
WECHAT_PREVIEW_WIDTH = 240
WECHAT_PREVIEW_HEIGHT = 240
WECHAT_THUMBNAIL_WIDTH = 50
WECHAT_THUMBNAIL_HEIGHT = 50

# GIF 默认参数
DEFAULT_GIF_FPS = 15
MAX_GIF_COLORS = 256

# 界面相关配置
DEFAULT_GRID_ROWS = 3
DEFAULT_GRID_COLS = 3

# API 相关 （占位，实际值应从安全方式获取）
WECHAT_API_APP_ID = "YOUR_APP_ID"
WECHAT_API_APP_SECRET = "YOUR_APP_SECRET" 